### PR TITLE
JVM metrics for Ganglia

### PR DESCRIPTION
**Pull request by senderista**
Currently in production, so you can go to http://dbserver20.cs.washington.edu/ganglia/ and take a look :)

### CODE REVIEW

**Comment by jingjingwang** [comment]
This is really cool! Just one question: I tried ganglia web a little bit but couldn't see JVM metrics being displayed. For example, I got "MyriaWorker_Memory_Heap_used: down". Does it mean that once this feature is pushed into production we will be able to see them?

**Comment by senderista** [comment]
It's in production but still in development :) I'm not sure what you're referring to; even when workers are down I can still see their data. Could you send me a URL?

**Comment by senderista** [comment]
LGTM (note that with my current code, the default port 8649 will be used if just a host is specified but not a port).

**Comment by senderista** [comment]
@jingjingwang are you OK to merge?

**Comment by jingjingwang** [comment]
Yep!

**Pull request merged**
