### PR TITLE
Myria python worker

### PR DESCRIPTION
**Pull request by parmitam**
unflattening MyriaPythonWorker,  adding env variable to python process fix python_egg_cache.

### CODE REVIEW

**Comment by senderista** [comment]
How are you getting REEF to deploy the `MyriaPythonWorker`  python module? Are you installing it by hand?

**Comment by parmitam** [comment]
We'll have to do the pip install for myriapythonworker via myria-cluster, since reef doesn't support hierarchical libraries.

**Comment by senderista** [comment]
I still don't think that having a separate package for the python worker code is a good idea, since it needs to be kept in sync with the rest of MyriaX. Flattening the namespace is not ideal, but why is it a dealbreaker? Also, having to manually install a package on the whole cluster isn't a great scenario for non-EC2 deployments.

**Comment by parmitam** [comment]
Myria-python and raco - are tightly linked with myriaX  and are distributed via pip, separately, so this isn't breaking precedent. Flattening the namespace to require python worker be a single file -- makes the code uglier than it already is and harder to maintain -- having the myriaPythonWorker as a single pip installable library is a pretty clean solution. Lets figure out the reef installation issue separately.

**Comment by senderista** [comment]
EC2 deployments aren't a problem if we keep this as a pip package: we can just install the pip package on each node from myria-cluster. My concern was more with non-EC2 deployments, as well as the possibility of the pip package getting out of sync with MyriaX. But your point about RACO and myria-python already being tightly coupled to MyriaX is well-taken.

**Comment by senderista** [comment]
Per @BrandonHaynes suggestion, let's try simulating the nested namespace with nested classes, so we can keep this as self-contained module files.

**Pull request closed without merging**
