### PR TITLE
check null in doIngest.

### PR DESCRIPTION
**Pull request by jingjingwang**
If for any reason we cannot get the dataset status due to a failed ingestion, return a proper error message.

### CODE REVIEW

**Comment by jingjingwang** [comment]
Fixes https://github.com/uwescience/myria/issues/841.

**Comment by dhutchis** [comment]
We should also do something for the deleteDataset line 369.  I had a dataset that appeared to have been deleted but the catalog didn't update.

**Comment by jingjingwang** [comment]
Did you mean https://github.com/uwescience/myria/blob/7644e4ebac6d5f34449960a439fff9b51b4a03a1/src/edu/washington/escience/myria/api/DatasetResource.java#L372? As I read through the code I think this chunk of code is unnecessary since the returned `status` is never used. What do you think? I'm thinking about making `Server.deleteDataset` not return anything.

**Comment by dhutchis** [comment]
If the catalog fails to update then the user should be notified, at least to warn them that the catalog is now in an inconsistent state.

**Comment by jingjingwang** [comment]
I think the user is notified if catalog is not updated since exceptions are thrown, it's only this line https://github.com/uwescience/myria/blob/master/src/edu/washington/escience/myria/parallel/Server.java#L1010 is unnecessary.

**Comment by dhutchis** [comment]
Okay, I see.  Looks good.

**Comment by dhutchis** [comment]
@jingjingwang I altered `deleteDataset` as we discussed to return nothing. If it looks good to you, go ahead and merge.

Thanks for your help Jingjing.

**Pull request merged**
