### PR TITLE
Emitting Postgres-specific syntax for 32-bit floats.

### LINKED ISSUE #690: postgres float vs double confusion with binary copy
fyi @ljorr1 @jortiz16 @domoritz 

1. Right now, Postgres uses 64-bit floats for both `FLOAT_TYPE` and `DOUBLE_TYPE`. See https://github.com/uwescience/myria/blob/master/src/edu/washington/escience/myria/accessmethod/JdbcAccessMethod.java#L382

2. The Binary copy code writes 32-bit floats for `FLOAT_TYPE` and 64-bit floats for `DOUBLE_TYPE`. See https://github.com/uwescience/myria/blob/6573fca6ba809d6d3eaf76d7ba90d1c86dff1518/src/edu/washington/escience/myria/PostgresBinaryTupleWriter.java#L101

This combination of features results in the following error during binary copy of `FLOAT_TYPE` data:

```java
ERROR 2015-02-08 16:54:45,648 [Nonblocking query executor#10] JdbcAccessMethod - Error inserting batch via PostgreSQL COPY
edu.washington.escience.myria.DbException: java.io.IOException: Write to copy failed.
	at edu.washington.escience.myria.accessmethod.JdbcAccessMethod.postgresCopyInsert(JdbcAccessMethod.java:135)
	at edu.washington.escience.myria.accessmethod.JdbcAccessMethod.tupleBatchInsert(JdbcAccessMethod.java:153)
	at edu.washington.escience.myria.operator.DbInsert.consumeTuples(DbInsert.java:166)
	at edu.washington.escience.myria.operator.RootOperator.fetchNextReady(RootOperator.java:123)
	at edu.washington.escience.myria.operator.Operator.nextReady(Operator.java:335)
	at edu.washington.escience.myria.parallel.LocalFragment.executeActually(LocalFragment.java:458)
	at edu.washington.escience.myria.parallel.LocalFragment.access$400(LocalFragment.java:43)
	at edu.washington.escience.myria.parallel.LocalFragment$1.call(LocalFragment.java:195)
	at edu.washington.escience.myria.parallel.LocalFragment$1.call(LocalFragment.java:175)
	at edu.washington.escience.myria.util.concurrent.ExecutableExecutionFuture.call(ExecutableExecutionFuture.java:193)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at edu.washington.escience.myria.util.concurrent.RenamingThreadFactory$1.run(RenamingThreadFactory.java:33)
Caused by: java.io.IOException: Write to copy failed.
	at org.postgresql.copy.PGCopyOutputStream.write(PGCopyOutputStream.java:82)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
	at java.io.DataOutputStream.writeInt(DataOutputStream.java:197)
	at java.io.DataOutputStream.writeFloat(DataOutputStream.java:242)
	at edu.washington.escience.myria.PostgresBinaryTupleWriter.writeTuples(PostgresBinaryTupleWriter.java:111)
	at edu.washington.escience.myria.accessmethod.JdbcAccessMethod.postgresCopyInsert(JdbcAccessMethod.java:125)
	... 13 more
Caused by: org.postgresql.util.PSQLException: ERROR: insufficient data left in message
  Where: COPY public:MyriaSysTemp:snapshot1309Hash2, line 1, column ESNRate
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:966)
	at org.postgresql.core.v3.QueryExecutorImpl.writeToCopy(QueryExecutorImpl.java:856)
	at org.postgresql.core.v3.CopyInImpl.writeToCopy(CopyInImpl.java:51)
	at org.postgresql.copy.PGCopyOutputStream.writeToCopy(PGCopyOutputStream.java:123)
	at org.postgresql.copy.PGCopyOutputStream.write(PGCopyOutputStream.java:80)
	... 19 more
```

because Postgres is expecting 64 bits but we only send them 32.

(This issue does not cause problems during execution because we fall back to the old-style JDBC batch insert method.)

I don't particularly care how this issue is resolved -- I think some other JDBC database we tried to support did not have both types of floats -- but I think that Laurel and Jen are probably suffering bad performance during ingest and writeback of the Nchilada and Tipsy data.

### PR DESCRIPTION
**Pull request by senderista**
Fixes #690.

### CODE REVIEW

**Comment by senderista** [comment]
OK, I'm working on the script you described, but I'm not really familiar with the Myria production deployment process. I assume that we shut down the cluster, back up the catalog, alter tables on all workers, verify the altered schema, deploy the new code, and finally bring the cluster back up. Should we run any system tests after bringing the cluster up but before accepting new jobs? Where are instructions for the deployment step?

**Comment by senderista** [comment]
I mean, I've read https://github.com/uwescience/myria/blob/master/myriadeploy/README.md, but I assume there are additional caveats/instructions for the production cluster.

**Comment by senderista** [comment]
So for pushing updated binaries to the cluster, should I use https://github.com/uwescience/myria/blob/master/myriadeploy/update_myria_binaries.py or https://github.com/uwescience/myria/blob/master/myriadeploy/using_deployment_utils.sh with the `-copy_distribution` flag?

**Comment by dhalperi** [comment]
I'll let @jingjingwang @domoritz @stechu @jortiz16 answer these questions – good practice! :)

**Comment by senderista** [comment]
I think I now have the additional info I need for this. I'll send you a script for review, possibly offline.

**Comment by senderista** [comment]
Sent script for review to @dhalperi offline.

**Comment by senderista** [comment]
Assigning to myself since this requires production changes before merge.

**Comment by senderista** [comment]
Cherry-picked actual code change into master; we don't need the script at this point since we're doing a clean Postgres upgrade to 9.4 (rebuilding all relations from scratch).
```
commit 4a0a988d880ce9ad672ed675f155aceea59b7fc0
Author: Tobin Baker <tdbaker@cs.washington.edu>
Date:   Fri Mar 20 16:24:54 2015 -0700

    Emitting Postgres-specific syntax for 32-bit floats.
```

**Pull request closed without merging**
