### PR TITLE
Utility to create deployment files from the command line

### PR DESCRIPTION
**Pull request by BrandonHaynes**
I need a command-line utility to generate deployment files for EC2- and HPC-oriented deployments.  Since this seems broadly useful, I thought we might include it in the distribution.

### CODE REVIEW

**Comment by jingjingwang** [comment]
If we need to specify different working directories/database names for workers, like what we have in the production, then this seems to be not enough. It would be great if this script can be extend (although there is probably no neat way...). I'm not sure if this functionality is in your plan..?

**Comment by BrandonHaynes** [comment]
The immediate use case here is to enable easier creating of configuration files for HPC deployment, where the set of nodes is not known until job submission time.  It's also really useful for the EC2 side, where this would allow me to avoid having to hardcode the deployment creation process there -- this is brittle, and will break sooner or later.

Extending the utility to support the last few configuration options is totally on the table, although this would increase the complexity of the arguments a bit.  Is it possible to handle that as a follow-on feature, since I need this for HPC scheduler init scripts now?

**Comment by jingjingwang** [comment]
Yes, definitely. I'm just wondering if you plan to do it in this PR or a following PR. Could you add a usage message to it? Basically saying it's not ready if we need to specify database names/working directories.

**Comment by BrandonHaynes** [comment]
Usage is displayed when you execute the utility with no arguments.  I'll look at supporting the full set of deployment options; I agree this is reasonable.

**Pull request merged**
