### PR TITLE
Add support for downloading Tipsy data via HTTP/HTTPS URL

### PR DESCRIPTION
**Pull request by BrandonHaynes**

### CODE REVIEW

**Comment by senderista** [comment]
@BrandonHaynes you have legitimately failing tests in Travis, have you looked at them?

**Comment by BrandonHaynes** [comment]
@senderista Any idea why these tests are failing?  They are unrelated to my modifications.

**Comment by senderista** [comment]
Hmm, the failing tests only occur in the JDK8 build, which is...interesting. If they seem to be just flaky, I'll open an issue and merge this PR.

**Comment by BrandonHaynes** [comment]
@senderista Now they show as passing -- weird.  Think this should be ready to merge.

**Pull request merged**
